
stages:

  data_ingestion:
    cmd: python src/CNN_Classifier/pipeline/stage01_data_ingestion.py
    deps:
      - src/CNN_Classifier/pipeline/stage01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images


  prepare_base_model:
    cmd: python src/CNN_Classifier/pipeline/stage02_prepare_base_model.py
    deps:
      - src/CNN_Classifier/pipeline/stage02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/CNN_Classifier/pipeline/stage03_training.py
    deps:
      - src/CNN_Classifier/pipeline/stage03_training.py
      - src/CNN_Classifier/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/CNN_Classifier/pipeline/stage04_model_evaluation.py
    deps:
      - src/CNN_Classifier/pipeline/stage04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - Scores.json:
          cache: false
